---
# tasks file for ansible-route

- name: add persistent route
  lineinfile:
    dest: /etc/rc.local
    regexp: '^ip route add {{ item.destination }}'
    line: 'ip route add {{ item.destination }} via {{ item.gw }}'
    insertbefore: '^exit 0'
  with_items: "{{ routes }}"

- name: add current route
  command: ip route add '{{ item.destination }}' via '{{ item.gw }}'
  ignore_errors: yes
  with_items: "{{ routes }}"
