---
# tasks file for ansible-route

- name: add persistent route
  lineinfile:
    dest: /etc/rc.local
    regexp: '^route add -net {{ item.destination }}'
    line: 'route add -net 172.31.254.72/29 gw {{ item.gw }}'
    insertbefore: '^exit 0'
  with_items: "{{ routes }}"

- name: add current route
  command: route add -net '{{ item.destination }}' gw route '{{ item.gw }}'
  ignore_errors: yes
  with_items: "{{ routes }}"
